name: 'Bump version'
run-name: Bump version: ${{ github.event.inputs.version }}
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The next version'
        required: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: cloudwatch-logs-aggregator/lambda/go.mod
      - run: make bump-version
        env:
          VERSION: ${{ github.event.inputs.version }}
      - run: make build
      - uses: peter-evans/create-pull-request@v4
        with:
          branch: 'release-v${{ github.event.inputs.version }}'
          commit-message: 'chore: bump to v${{ github.event.inputs.version }}'
          title: 'chore: bump to v${{ github.event.inputs.version }}'
          body: |
            Bump version to v${{ github.event.inputs.version }}

            After merging this PR, create a release with `v${{ github.event.inputs.version }}` tag.
          delete-branch: true
